### ISSUE TITLE
Ex. 2.1: No Add Client IP+

### ISSUE THREAD

**Issue by RickPack** [benperk/ADE#1]
When I click "Set server firewall", I do not see "Allow Azure Services ..." or "Add Client IP". I'm instead taken to the Networking blade with menus: "Public Access", "Private Access", "Connectivity".

**Comment by RickPack** [comment]
More steps needed than what the book indicated: I found "Allow Azure Services..." after clicking "Public access", and then "Selected Networks". And "Add your client ...." appears now instead of "Add your IP". Assuming I have not made a mistake, these reflect changes in the Azure environment since book publication, which happens. :)

**Comment by RickPack** [comment]
Not sure if I missed a step, but using my Microsoft login failed for the username / pw in Azure Data Studio, which had to be downloaded locally. The domain was rejected (yahoo.com). However, Microsoft Entra worked in the "Authentication type" dropdown menu of Azure Data Studio.

**Comment by benperk** [comment]
Hi @RickPack, the name might have changed.  the objective is to add your client IP address to the Firewall rules so that you can connect to the database from Azure Data Studio.  Here is what I was trying to describe: **+ Add your client IPv4 address (<your client IP address>)** 
![ADE2 1](https://github.com/benperk/ADE/assets/8362179/cf0f93bb-6fdf-4f98-8bcb-8636c2a45730)
